function [guihands,plotinfo]=adduicontrols_sonar(plotinfo,h0);
  
  x0 = 0.88;
  y0 = 0.15;
  dx = 0.07;
%   dy = 0.025;
  dy = 0.032;
  backcol = [1 1 1];
  forecol=[0 0 0];
  
  
  guihands(1) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',10,...		   
			   'Position',[x0 y0 dx dy], ...
			   'Style','edit',...
			   'String',num2str(plotinfo.ylim(2)),...
			   'foregroundcol',forecol);
  guihands(2) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',10,...		   
			   'Position',[x0-dx/2 y0+1.5*dy 1.5*dx 1.4*dy], ...
			   'Style','text',...
			   'String','Max Depth',...
			   'foregroundcol',forecol);
%   guihands(3) =  uicontrol('Parent',h0,...
% 			   'Units','normal', ...
% 			   'BackgroundColor',backcol, ...
% 			   'ListboxTop',0, ...
% 			   'fontsize',10,...		   
% 			   'Position',[x0 y0+1.5*dy dx dy], ...
% 			   'Style','edit',...
% 			   'String',num2str(plotinfo.clim(2)),...
% 			   'foregroundcol',forecol);
%   guihands(4) =  uicontrol('Parent',h0,...
% 			   'Units','normal', ...
% 			   'BackgroundColor',backcol, ...
% 			   'ListboxTop',0, ...
% 			   'fontsize',9,...		   
% 			   'Position',[x0-dx y0+1.5*dy dx dy], ...
% 			   'Style','text',...
% 			   'String','Max |U|',...
% 			   'foregroundcol',forecol);
