% function qv_docal(data,irep,q,head,h)
% qv_docal performs calibrations on all selected series.
q.cal_tog=~q.cal_tog;
set(h.cal_sel,'visible',q.toggle(q.cal_tog+1,:));
if q.cal_tog
set(gcf,'windowbuttonmotionfcn','')
  return 
end
% otherwise, we should get the values from h.cal_sel
% and calibrate them
from_series=get(h.cal_sel,'value');
cal_series=q.series(from_series,:);

for i=1:size(cal_series,1)
  % loop through each series
  tempser=(lower(cal_series(i,:)));
  if ~any(strcmp(fieldnames(data),deblank(tempser))) 
    % need to make a new series name
    q.nser=q.nser+1;
    q.series(q.nser,:)=tempser;
    q.display_series=[q.display_series q.nser];
    % now make it a display option and turn it on
      h.select(q.nser) = uicontrol( ...
   'Style', 'push', ...
   'Fontsize',10, ...
   'backgroundcolor',cmap(q.nser,:),...
   'foregroundcolor',[1 1 1],...
   'HorizontalAlignment','left', ...
   'Callback', ['h.selected(' num2str(q.nser) ')=qv_sel(h.select(' num2str(q.nser) '),h.selected(' num2str(q.nser) '),h.update(' num2str(q.nser) '));'],...
   'Enable', 'on', ...
   'Position', [5 q.fig_position(4)-xxpos-q.step*q.nser wid1 q.step+1], ...
   'String',q.series(q.nser,:), ...
   'Tag', ['select' num2str(q.nser)] );
h.selected(q.nser)=1;
h.update(q.nser) = uicontrol( ...
   'Style', 'text', ...
   'Fontsize',10, ...
   'foregroundcolor',cmap(q.nser,:),...
   'backgroundcolor',[.875 .875 .875],...
   'HorizontalAlignment','left', ...
   'visible','on',...
   'Enable', 'inactive', ...
   'Position', [wid1+10 q.fig_position(4)-xxpos-q.step*q.nser wid2 q.step+1], ...
   'Tag', ['update' num2str(q.nser)] );
end
tempser=deblank(tempser);
len=length(tempser);
% first check to see if a simple polynomial fit works (temp, cond, pressure,
% accelerometers)
if (tempser(1)=='t' & tempser(len)~='p') | ...
      tempser(1)=='p' | ...
      tempser(1)=='a'  | ...
      tempser(1)=='c'
  eval(['data.' tempser '=qv_calp(data.' upper(tempser) ...
      ',head.coef.' upper(tempser) ');,irep.' tempser '=irep.' upper(tempser) ...
      ';']);
elseif (tempser(1)=='t' & tempser(len)=='p')
%  temp=upper(tempser(1:len-1));
%  dc_ser=find(head.sensor_name(:,:)==temp);
  eval(['data.' tempser '=qv_caltp(data.' upper(tempser) ...
      ',head.coef.' upper(tempser) ',irep.' upper(tempser) ',data.' upper(tempser(1:len-1)) ...
      ',head.coef.' temp ',irep.' upper(tempser(1:len-1)) ',data.fspd);,irep.' tempser ...
      '=irep.' upper(tempser) ';']);
 else
   eval(['data.' tempser '=data.' upper(tempser) ';']);
   eval(['irep.' tempser '=irep.' upper(tempser) ';']);
end  
end
qv_now
set(gcf,'windowbuttonmotionfcn','qv_updat')
