% Display driver for qv - includes all GUI information and initial
% axis rendering

% $Revision: 1.1.1.1 $ $Date: 2008/01/31 20:22:47 $ $Author: aperlin $	
% Originally J. Nash

if strcmp(computer,'PCWIN')
  q.font='Terminal';
  q.fsize=7;
  q.fixedfont='fixedsys';
  q.step=25;
else
  q.font='lucidatypewriter';
  q.fsize=11;
  q.fixedfont='lucidatypewriter';
  q.step=15;
end
q.step=2*q.fsize;

figure(1)
clf
pp=get(0,'screensize')
pp(4)=pp(4)-460;
pp(3)=pp(3)-410;
set(gcf,'Name',['QuickView 1.01 (an oxymoron): ' head.filename],'menubar','none','numbertitle','off')
set(gcf,'position',pp)
q.fig_position=get(gcf,'position');
%q.fig_position(4)=max(420,q.fig_position(4));
%q.fig_position(4)=max(420,q.fig_position(4));

xxpos=30
wid1=65
wid2=50
% setptr(1,'fullcross')
% a=uicontrol('style','list','units','normalized','Position',[.1 .5 .5 ...
%     .4],'userdata',Sensor_name)
% Set up a few of the defaults
q.plot_type='spread';
q.units='Volts';
q.axis_type='vert';
q.toggle=['of';'on'];
q.lim_tog=0;
q.cal_tog=0;
% the following is commented out when the default yaxis is time.  
%  y_axis=p;,y_axis_label='depth (m)';
%  ymin=min(y_axis); % +.001*(max(y_axis)-min(y_axis));
%  ymax=max(y_axis); % -.001*(max(y_axis)-min(y_axis));
% y_axis8=p8;

  colormap(hsv);
  temp=[ .5 .5 .5;...
    0         0    1.0000;...
         0    0.5000         0;...
	 1.0000         0         0;...
	 0    0.7500    0.7500;...
	 0.8500         0    0.7500;...
	 0.7500    0.7500         0;...
	 0.2500    0.2500    0.2500;...
	 0.5         0    1.0000;...
	 1.0000    0.5000         0;...
	 0    1.0000         0;...
	 0 .7 .9;...
	 .8 .3 .1; ...
	 0 .75 0; ...
	 1 .3 .8];
cmap=[temp;temp;temp;temp];
for i=1:length(q.series)
  if any(i==q.display_series)
    h.select(i) = uicontrol( ...
    'Style', 'push', ...
    'Fontsize',q.fsize, ...
    'backgroundcolor',cmap(i,:),...
    'foregroundcolor',[1 1 1],...
    'HorizontalAlignment','left', ...
    'Callback', ['h.selected(' num2str(i) ')=qv_sel(h.select(' num2str(i) '),h.selected(' num2str(i) '),h.update(' num2str(i) '));'],...
    'Enable', 'on', ...
    'Position', [5 q.fig_position(4)-xxpos-q.step*i wid1 q.step+1], ...
    'String',q.series(i,:), ...
    'Tag', ['select' num2str(i)] );
    h.selected(i)=1;
    h.update(i) = uicontrol( ...
    'Style', 'text', ...
    'Fontsize',q.fsize, ...
    'foregroundcolor',cmap(i,:),...
    'backgroundcolor',[.875 .875 .875],...
    'HorizontalAlignment','left', ...
    'visible','on',...
    'Enable', 'inactive', ...
    'Position', [wid1+10 q.fig_position(4)-xxpos-q.step*i wid2 q.step+1], ...
    'Tag', ['update' num2str(i)] );
  else
    h.select(i) = uicontrol( ...
    'Style', 'push', ...
    'Fontsize',q.fsize, ...
    'foregroundcolor',cmap(i,:),...
    'backgroundcolor',[1 1 1],...
    'HorizontalAlignment','left', ...
    'Callback', ['h.selected(' num2str(i) ')=qv_sel(h.select(' num2str(i) '),h.selected(' num2str(i) '),h.update(' num2str(i) '));'],...
    'Enable', 'on', ...
    'Position', [5 q.fig_position(4)-xxpos-q.step*i wid1 q.step+1], ...
    'String', q.series(i,:), ...
    'Tag', ['select' num2str(i)] );
    h.selected(i)=0;
    h.update(i) = uicontrol( ...
    'Style', 'text', ...
    'Fontsize',q.fsize, ...
    'foregroundcolor',cmap(i,:),...
    'backgroundcolor',[1 1 1],...
    'HorizontalAlignment','left', ...
    'visible','off',...
    'Enable', 'off', ...
    'Position', [wid1+10 q.fig_position(4)-xxpos-q.step*i wid2 q.step+1], ...
    'Tag', ['update' num2str(i)] );
 end 

end

h.pmax=uicontrol( ...
   'Style', 'text', ...   'Fontsize',12, ...
   'HorizontalAlignment','left', ...
   'Units','normalized', ...
   'Visible','on',...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.09 .94 .08 .04]);
h.pmin=uicontrol( ...
   'Style', 'text', ...   'Fontsize',12, ...
   'HorizontalAlignment','left', ...
   'Units','normalized', ...
   'Visible','on',...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.09 .01 .08 .04]);
h.now=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.9 .94 .1 .05], ...
   'String', 'All Drop','callback','mins.y=min(y_axis);,maxs.y=max(y_axis);,qv_now');
h.fit=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.7 .94 .1 .05], ...
   'String', 'FIT','callback','q.plot_type=''fit'';,temp=axis;,mins.y=-temp(4);,maxs.y=-temp(3);,qv_now;');
h.spread=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.8 .94 .1 .05], ...
   'String', 'SPREAD','callback','q.plot_type=''spread'';,temp=axis;,mins.y=-temp(4);,maxs.y=-temp(3);,qv_now;');
h.spread=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [0.077 0.05 .075 .05], ...
   'String', 'Deselect All','callback','qv_deselectall');
h.spread=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [0.01 0.05 .075 .05], ...
   'String', 'Select All','callback','qv_selectall');
h.cal=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.29 .94 .1 .05], ...
   'String', 'calibrate', ...
   'callback','qv_docal;');
h.limits=uicontrol( ...
   'Style', 'pushbutton', ...   'Fontsize',12, ...
   'HorizontalAlignment','center', ...
   'Units','normalized', ...
   'Visible','on',...
   'Min', 0, ...
   'Max', 0, ...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [.19 .94 .1 .05], ...
   'String', 'LIMITS', ...
   'callback','q.lim_tog=~q.lim_tog;,set(h.show_limits,''visible'',q.toggle(q.lim_tog+1,:)),');% 'enable'',q.toggle(q.lim_tog+1,:)');
h.cal_sel=uicontrol( ...
   'Style', 'list', ...
   'fontname',q.font, 'fontsize',q.fsize,...
   'HorizontalAlignment','left', ...
   'Units','normalized', ...
   'Min',0,'Max',2,...
   'Visible','off',...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'string',q.series,...
   'Position', [.11 .3 .19 .6]);
h.show_limits=uicontrol( ...
   'Style', 'list', ...
   'fontname',q.font, 'fontsize',q.fsize,...
   'HorizontalAlignment','left', ...
   'Units','points', ...
   'max',0,...
   'min',0,...
   'Visible','off',...
   'Enable', 'on', ...
   'selectionhighlight','off',...
   'Position', [1 1 120 150]);
h.file(1)=uimenu('label','File');
h.file(2)=uimenu(h.file(1),'label','Load Raw file','callback','qv_new');
h.file(3)=uimenu(h.file(1),'label','View Header','callback','qv_head');
h.file(4)=uimenu(h.file(1),'label','Print','callback','print -dpsc -Php1600');
h.file(5)=uimenu(h.file(1),'label','Exit','callback','delete(gcf);,clear');
new_fig=2;
h.fft(1)=uimenu('label','PSD');
h.fft(2)=uimenu(h.fft(1),'label','NOW','callback','qv_fft');

%h3(4)=uimenu('label','Toggles');
%h4(1)=uimenu(h3(4),'label','Plot Layout');
%h41(1)=uimenu(h4(1),'label','Vertical','callback','temp=1;,qv_togs');
%h41(2)=uimenu(h4(1),'label','Horizontal','callback','temp=2;,qv_togs');
%h4(2)=uimenu(h3(4),'label','Scale');
%h42(1)=uimenu(h4(2),'label','Pressure','callback','temp=3;,qv_togs');
%h42(2)=uimenu(h4(2),'label','Time','callback','temp=4;,qv_togs');
%h4(3)=uimenu(h3(4),'label','Calbriate');
%h43(1)=uimenu(h4(3),'label','Engineering Units','callback','temp=5;,qv_togs');
%h43(2)=uimenu(h4(3),'label','Voltage','callback','temp=6;,qv_togs');
%h4(3)=uimenu(h3(4),'label','Fit/spread');
%h43(1)=uimenu(h4(3),'label','FIT','callback','temp=7;,qv_togs');
%h43(2)=uimenu(h4(3),'label','SPREAD','callback','temp=8;,qv_togs');


