function sigma=read_tao_d(fname)
% read_tao_d.m
% create mat files from density data
% $Revision: 1.4 $ $Date: 2009/11/16 17:27:15 $ $Author: aperlin $	
% Originally A. Perlin
fid=fopen(fname,'r');
qlt=strvcat('Quality Code Definitions:',...
'0 = datum missing',...
'1 = highest quality; Pre/post-deployment calibrations agree to within',...
'sensor specifications.  In most cases only pre-deployment calibrations have',...
'been applied',...
'2 = default quality; Pre-deployment calibrations applied.  Default',...
'value for sensors presently deployed and for sensors which were either not',...
'recovered or not calibratable when recovered.',...
'3 = adjusted data; Pre/post calibrations differ, or original data do',...
'not agree with other data sources (e.g., other in situ data or climatology),',...
'or original data are noisy.  Data have been adjusted in an attempt to',...
'reduce the error.',...
'4 = lower quality; Pre/post calibrations differ, or data do not agree',...
'with other data sources (e.g., other in situ data or climatology), or data',...
'are noisy.  Data could not be confidently adjusted to correct for error.',...
'5 = sensor or tube failed');
srs=strvcat('Source code definitions:',...
'    0 - No Sensor, No Data ',...
'    1 - Real Time (Telemetered Mode)',...
'    2 - Derived from Real Time',...
'    3 - Temporally Interpolated from Real Time',...
'    4 - Source Code Inactive at Present',...
'    5 - Recovered from Instrument RAM (Delayed Mode)',...
'    6 - Derived from RAM',...
'    7 - Temporally Interpolated from RAM');
ins=strvcat('Instrument code definitions:',...
'    0 - No Sensor',...
'    4 - Conductivity (FSI)',...
'   14 - NextGen Conductivity',...
'   24 - NextGen Conductivity (Firmware version 5.03+)',...
'   70 - Seacat Conductivity',...
'   71 - Microcat Conductivity',... 
'   99 - Unknown');
dd=textscan(fid,'%s',2,'delimiter','\r\n');
a=char(dd{:});
sigma.readme=strvcat('Density (Sigma-Theta)',' ',a(1,:),a(2,:),' ',qlt,srs,ins);
ik=find(a(1,:)==',');
nblocks=str2num(a(1,ik(2)+1:ik(2)+4));
for i=1:nblocks
   dd=textscan(fid,'%s',4,'delimiter','\r\n');
   a=char(dd{:});
   ik=find(a(1,:)==',');
   nlines=str2num(a(1,ik(1)+1:ik(2)-6));
   iks=strfind(a(3,:),':');
   ikk=min([strfind(a(3,:),'I'),strfind(a(3,:),'Q')]);
   if isempty(ikk)
       depth=str2num(a(3,iks+1:end));
   else
       depth=str2num(a(3,iks+1:ikk-1));
   end
   sigma(i).depth=depth;
   frm='';
   for ii=1:length(depth)
       frm=[frm ' %f'];
   end
   id=strfind(a(4,:),'ID');
   if ~isempty(id)
       aa=[' %' num2str(length(depth)*2) 'c '];
   else
       aa='';
   end
   tmp=textscan(fid,['%s %s' frm aa '%s %s'],nlines);
   sigma(i).time=datenum([char(tmp{1}) char(tmp{2})],'yyyymmddHHMM');
   for ii=1:length(depth)
       sigma(i).sigma_theta(:,ii)=tmp{ii+2};
   end
   if ~isempty(id)
       sigma(i).instrument=cellstr(tmp{end-2});
   end
   sigma(i).quality=tmp{end-1};
   sigma(i).source=tmp{end};
   bad=find(sigma(i).sigma_theta<-9);
   sigma(i).sigma_theta(bad)=NaN;
   dd=textscan(fid,'%s',1,'delimiter','\r\n');
end
fclose(fid);
idd=find(fname=='.');
save(fname(1:idd-1),'sigma')
