function t=read_tao_t(fname)
% read_tao_t.m
% create mat files from fixed depth subsurface temperature data
% $Revision: 1.4 $ $Date: 2009/04/28 00:01:56 $ $Author: aperlin $	
% Originally A. Perlin
%
% updated by S. Warner in June 2014 to be able to read the new ascii files
% generated by the new TAO download results

fid=fopen(fname,'r');
qlt=strvcat('Data Quality Codes(Q):',...
'0 = unknown',...
'1 = good data',...
'2 = probably good data',...
'3 = questionable data',...
'4 = bad data',...
'5 = adjusted data',...
'9 = missing data');
srs=strvcat('Data Mode Codes(M):',...
'R = real-time data',...
'P = provisional data',...
'D = delayed mode data',...
'M = mixed real-time and delayed mode data');
dd=textscan(fid,'%s',2,'delimiter','\r\n');
a=char(dd{:});
ik=find(a(1,:)=='(');
t.readme=strvcat('Upper Ocean Temperatures',' ',a(1,1:ik-1),' ',qlt,srs);
ik=find(a(1,:)==',');
ik2 = find(a(1,:) == ')');
% nblocks=str2num(a(1,ik(2)+1:ik(2)+4));
nblocks=str2num(a(1,ik+1:ik2-12));
for i=1:nblocks
%    dd=textscan(fid,'%s',4,'delimiter','\r\n');
   dd=textscan(fid,'%s',3,'delimiter','\r\n');
   a=char(dd{:});
%    ik=find(a(1,:)==',');
%    nlines=str2num(a(1,ik(1)+1:ik(2)-6));
   ik=find(a(1,:)=='(');
   ikc = find(a(1,:)==',');
   nlines=str2num(a(1,ik+1:ikc-11));
%    ikk=find(a(3,:)=='Q');
%    depth=str2num(a(3,20:ikk-1));
   ikk=find(a(2,:)=='Q');
   depth=str2num(a(2,20:ikk(1)-1));
   t(i).depth=depth;
   frm='';
   for ii=1:length(depth)
       frm=[frm ' %f'];
   end
%    tmp=textscan(fid,['%s %s' frm ' %s %s'],nlines);
   tmp=textscan(fid,['%s %s' frm ' %s %s'],nlines);
   t(i).time=datenum([char(tmp{1}) char(tmp{2})],'yyyymmddHHMM');
   for ii=1:length(depth)
       t(i).t(:,ii)=tmp{ii+2};
   end
   t(i).quality=tmp{end-1};
   t(i).mode=tmp{end};
   bad=find(t(i).t<-9);
   t(i).t(bad)=NaN;
   dd=textscan(fid,'%s',1,'delimiter','\r\n');
end
fclose(fid);
id=find(fname=='.');
save(fname(1:id-1),'t')


