function met=read_NDBCbuoy_meteo(dpath,station_id,year)
% read_NDBCbuoy_meteo(dpath,station_id,year)
% reads meteo data from NDBC buoy and returns it in structure met
% data should be save in files as: 51028h2004.txt,
% where 51028 is the station ID, h is NDBC marker for meteo data, and 2004
% is the year when data was collected
% this is hourly data
% dpath - data path
% station_id is the station ID (string)
% year - year of measurements
d=dir([dpath station_id 'h' num2str(year) '*']);
fid = fopen([dpath d.name]);
header=textscan(fid,'%s',1,'delimiter','\n');
hdr=char(header{1});
if hdr(1)=='#'
    header2=textscan(fid,'%s',1,'delimiter','\n');
end
FormatString=repmat('%f',1,18);
tx=textscan(fid,FormatString); % Read data
x=cell2mat(tx);
fclose(fid);

met.time=datenum(x(:,1),x(:,2),x(:,3),x(:,4),x(:,5),0);
met.wd=x(:,6); bad=find(met.wd>360); met.wd(bad)=NaN;
met.wspd=x(:,7); bad=find(met.wspd>=99); met.wspd(bad)=NaN;
met.gst=x(:,8); bad=find(met.gst>=99); met.gst(bad)=NaN;
met.wvht=x(:,9); bad=find(met.wvht==99 | met.wvht==999 | met.wvht==9999); met.wvht(bad)=NaN;
met.dpd=x(:,10); bad=find(met.dpd==99 | met.dpd==999 | met.dpd==9999); met.dpd(bad)=NaN;
met.apd=x(:,11); bad=find(met.apd==99 | met.apd==999 | met.apd==9999); met.apd(bad)=NaN;
met.mwd=x(:,12); bad=find(met.mwd==99 | met.mwd==999 | met.mwd==9999); met.mwd(bad)=NaN;
met.bar=x(:,13); bad=find(met.bar==99 | met.bar==999 | met.bar==9999); met.bar(bad)=NaN;
met.atmp=x(:,14); bad=find(met.atmp==99 | met.atmp==999 | met.atmp==9999); met.atmp(bad)=NaN;
met.wtmp=x(:,15); bad=find(met.wtmp==99 | met.wtmp==999 | met.wtmp==9999); met.wtmp(bad)=NaN;
met.dewp=x(:,16); bad=find(met.dewp==99 | met.dewp==999 | met.dewp==9999); met.dewp(bad)=NaN;
met.vis=x(:,17); bad=find(met.vis==99 | met.vis==999 | met.vis==9999); met.vis(bad)=NaN;
met.tide=x(:,18); bad=find(met.tide==99 | met.tide==999 | met.tide==9999); met.tide(bad)=NaN;

% recalculate wind speed to 10 m height (measured at 3 m)
met.wspd=sw_u10(met.wspd',3)';
rho_a=1.225; % air density [kg/m^3], Kundu, p.619
met.windu=met.wspd.*sin(met.wd*pi/180+pi);
met.windv=met.wspd.*cos(met.wd*pi/180+pi);
Cd=sw_drag(met.wspd)';
met.tau_wu=rho_a*Cd.*met.windu.*abs(met.windu);
met.tau_wv=rho_a*Cd.*met.windv.*abs(met.windv);
met.readme=strvcat(['Meteorological hourly data from station ' station_id],...
'Owned and maintained by National Data Buoy Center',...
['http://www.ndbc.noaa.gov/station_history.php?station=' station_id],...
'3-meter discus buoy',...
'TIME: Time of the measurement.',...
'WD: Wind direction (the direction the wind is coming from in ',...
'  degrees clockwise from N) during the same period used for WSPD.',...
'WSPD: Wind speed (m/s) averaged over an eight-minute period for ',...
'  buoys and a two-minute period for land stations. Reported Hourly.',...
'  recomputed to 10 m height',...
'GST: Peak 5 or 8 second gust speed (m/s) measured during the ',...
'  eight-minute or two-minute period.',...
'  The 5 or 8 second period can be determined by payload.',...
'WVHT: Significant wave height (meters) is calculated as the average ',...
'  of the highest one-third of all of the wave heights during ',...
'  the 20-minute sampling period.',...
'DPD: Dominant wave period (seconds) is the period with the maximum wave energy.',...
'APD: Average wave period (seconds) of all waves during the 20-minute period.',...
'MVD: Mean wave direction (degrees) corresponding to energy ',...
'  of the dominant period (DPD).',...
'BAR: Sea level pressure (hPa). 5 m above site elevation.',...
'ATMP: Air temperature (Celsius). 4 m above site elevation.',...
'WTMP: Sea surface temperature (Celsius). 0.6 m below site elevation.',...
'DEWP: Dewpoint temperature taken at the same height as the air temperature measurement.',...
'VIS: Station visibility (kilometers).',...
'TIDE: The periodic rising and falling of the earth''s oceans. Tide is measured in feet.',...
'WINDU: Eastward component of wind',...
'WINDV: Northward component of wind',...
'TAU_WU: Eastvard component of wind stress, N/m^2',...
'TAU_WV: Northward component of wind stress, N/m^2');
