function wind=read_NDBCbuoy_wind(dpath,station_id,year)
% read_NDBCbuoy_meteo(dpath,station_id,year)
% reads meteo data from NDBC buoy and returns it in structure wind
% data should be save in files as: 51028c2004.txt,
% where 51028 is the station ID, h is NDBC marker for meteo data, and 2004
% is the year when data was collected
% this is 10 minute data
% dpath - data path
% station_id is the station ID (string)
% year - year of measurements
d=dir([dpath station_id 'c' num2str(year) '*']);
fid = fopen([dpath d.name]);
header=textscan(fid,'%s',1,'delimiter','\n');
hdr=char(header{1});
if hdr(1)=='#'
    header2=textscan(fid,'%s',1,'delimiter','\n');
end
FormatString=repmat('%f',1,10);
tx=textscan(fid,FormatString); % Read data
x=cell2mat(tx);
fclose(fid);

wind.time=datenum(x(:,1),x(:,2),x(:,3),x(:,4),x(:,5),0);
wind.dir=x(:,6); bad=find(wind.dir>360); wind.dir(bad)=NaN;
wind.spd=x(:,7); bad=find(wind.spd>=99); wind.spd(bad)=NaN;
wind.gdr=x(:,8); bad=find(wind.gdr>360); wind.gdr(bad)=NaN;
wind.gst=x(:,9); bad=find(wind.gst>=99); wind.gst(bad)=NaN;
wind.gtime=x(:,10); bad=find(wind.gtime>=99); wind.gtime(bad)=NaN;

% recalculate wind speed to 10 m height (measured at 3 m)
wind.spd=sw_u10(wind.spd',3)';
rho_a=1.225; % air density [kg/m^3], Kundu, p.619
wind.u=wind.spd.*sin(wind.dir*pi/180+pi);
wind.v=wind.spd.*cos(wind.dir*pi/180+pi);
Cd=sw_drag(wind.spd)';
wind.tau_wu=rho_a*Cd.*wind.u.*abs(wind.u);
wind.tau_wv=rho_a*Cd.*wind.v.*abs(wind.v);
wind.readme=strvcat(['Wind 10 min data from station ' station_id],...
'Owned and maintained by National Data Buoy Center',...
['http://www.ndbc.noaa.gov/station_history.php?station=' station_id],...
'3-meter discus buoy',...
'TIME: Time of the measurement.',...
'DIR: Wind direction (the direction the wind is coming from in ',...
'  degrees clockwise from N) during the same period used for WSPD.',...
'SPD: 10 minute wind speed (m/s)',...
'  recomputed to 10 m height',...
'GDR: Direction, in degrees clockwise from true North, of the GSP,',...
'  reported at the last hourly 10-minute segment.',...
'GST: Peak 5 or 8 second gust speed (m/s) measured during the ',...
'  eight-minute or two-minute period.',...
'  The 5 or 8 second period can be determined by payload.',...
'GTIME: time of gust in continuous Winds data',...
'U: Eastward component of wind',...
'V: Northward component of wind',...
'TAU_WU: Eastvard component of wind stress, N/m^2',...
'TAU_WV: Northward component of wind stress, N/m^2');
