function [guihands,plotinfo]=adduicontrols(plotinfo,h0);
  
  x0 = 0.88;
  y0 = 0.1;
  dx = 0.07;
%   dy = 0.025;
  dy = 0.032;
  backcol = [1 1 1];
  forecol=[0 0 0];
  
  
  guihands(1) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',8,...		   
			   'Position',[x0 y0 dx dy], ...
			   'Style','edit',...
			   'String',num2str(plotinfo.ylim(2)),...
			   'foregroundcol',forecol);
  guihands(2) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',8,...		   
			   'Position',[x0-dx y0 dx dy], ...
			   'Style','text',...
			   'String','Max Z',...
			   'foregroundcol',forecol);
  guihands(3) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',8,...		   
			   'Position',[x0 y0+1.5*dy dx dy], ...
			   'Style','edit',...
			   'String',num2str(plotinfo.xlim(1)),...
			   'foregroundcol',forecol);
  guihands(4) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',7,...		   
			   'Position',[x0-dx y0+1.5*dy dx dy], ...
			   'Style','text',...
			   'String','days before now:',...
			   'foregroundcol',forecol);
  guihands(5) =  uicontrol('Parent',h0,...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',8,...		   
			   'Position',[x0 y0+3*dy dx dy], ...
			   'Style','edit',...
			   'String',num2str(plotinfo.clim(2)),...
			   'foregroundcol',forecol);
  guihands(6) =  uicontrol(...
			   'Units','normal', ...
			   'BackgroundColor',backcol, ...
			   'ListboxTop',0, ...
			   'fontsize',8,...		   
			   'Position',[x0-dx y0+3*dy dx dy], ...
			   'Style','text',...
			   'String','Max |U|',...
			   'foregroundcol',forecol);
